from app.models.schemas import SimulationCreateRequest


def demo_state() -> dict:
    return {
        "disaster": {
            "type": "Flood",
            "severity": 78,
            "population_density": "High",
            "road_blockage": 54,
            "affected_population": 640,
            "active_incidents": 24,
            "blocked_roads": 18,
            "status": "Running",
        },
        "incidents": [
            {
                "id": "QX-1047",
                "type": "Trapped",
                "priority": "Critical",
                "location": "Zone C / Riverside Towers Complex",
                "position": {"x": 31, "y": 35},
                "people": 6,
                "medical_required": True,
                "status": "Assigned",
                "assigned_assets": ["Drone 03", "Ambulance 07", "Rescue Team 12"],
                "description": "People trapped on 3rd floor balconies with rising water levels.",
            },
            {
                "id": "QX-1051",
                "type": "Medical emergency",
                "priority": "Critical",
                "location": "Zone B / Central Market Square",
                "position": {"x": 43, "y": 51},
                "people": 4,
                "medical_required": True,
                "status": "In Progress",
                "assigned_assets": ["Ambulance 02", "Medical Team 04"],
                "description": "Severe hypothermia and trauma victims awaiting extraction.",
            },
            {
                "id": "QX-1055",
                "type": "Food / water",
                "priority": "High",
                "location": "Zone F / Old Bus Depot & Terminal",
                "position": {"x": 61, "y": 44},
                "people": 28,
                "medical_required": False,
                "status": "Assigned",
                "assigned_assets": ["Rescue Team 08", "Drone 06"],
                "description": "Stranded commuters require emergency rations and potable water.",
            },
            {
                "id": "QX-1059",
                "type": "Structural damage",
                "priority": "High",
                "location": "Zone E / Canal Bridge & Sluice Gate",
                "position": {"x": 52, "y": 65},
                "people": 9,
                "medical_required": False,
                "status": "New",
                "assigned_assets": [],
                "description": "Bridge support compromised by flood debris; traffic halted.",
            },
            {
                "id": "QX-1062",
                "type": "Trapped",
                "priority": "Critical",
                "location": "Zone A / Northern Residential Heights",
                "position": {"x": 22, "y": 42},
                "people": 8,
                "medical_required": True,
                "status": "Assigned",
                "assigned_assets": ["Rescue Team 03", "Drone 01"],
                "description": "Multiple families trapped in basement units as flood walls breached.",
            },
            {
                "id": "QX-1066",
                "type": "Missing person",
                "priority": "High",
                "location": "Zone D / East Industrial Park Bay 4",
                "position": {"x": 68, "y": 32},
                "people": 3,
                "medical_required": False,
                "status": "In Progress",
                "assigned_assets": ["Drone 04", "Search Team 07"],
                "description": "Warehouse security personnel unaccounted for following storm surge.",
            },
            {
                "id": "QX-1070",
                "type": "Fire",
                "priority": "Medium",
                "location": "Zone B / Metro Electrical Substation",
                "position": {"x": 48, "y": 56},
                "people": 0,
                "medical_required": False,
                "status": "Assigned",
                "assigned_assets": ["Fire Team 09"],
                "description": "Transformer explosion following storm floodwater infiltration.",
            },
            {
                "id": "QX-1074",
                "type": "Trapped",
                "priority": "Critical",
                "location": "Zone G / Coastal Harbor Pier 9 Warehouse",
                "position": {"x": 82, "y": 28},
                "people": 12,
                "medical_required": True,
                "status": "New",
                "assigned_assets": [],
                "description": "Dock workers cut off on container roof by tidal surge.",
            },
            {
                "id": "QX-1078",
                "type": "Medical emergency",
                "priority": "Critical",
                "location": "Zone J / Pinecrest Senior Care Pavilion",
                "position": {"x": 70, "y": 72},
                "people": 15,
                "medical_required": True,
                "status": "Assigned",
                "assigned_assets": ["Ambulance 05", "Rescue Team 16"],
                "description": "Power failure disabled medical respirators; urgent evacuation required.",
            },
            {
                "id": "QX-1082",
                "type": "Structural damage",
                "priority": "High",
                "location": "Zone H / University Tech Campus Quad",
                "position": {"x": 34, "y": 76},
                "people": 18,
                "medical_required": False,
                "status": "In Progress",
                "assigned_assets": ["Rescue Team 11"],
                "description": "Research building roof collapse; students sheltered in laboratory wing.",
            },
            {
                "id": "QX-1086",
                "type": "Food / water",
                "priority": "Medium",
                "location": "Zone I / Grand Central Railway Concourse",
                "position": {"x": 58, "y": 22},
                "people": 42,
                "medical_required": False,
                "status": "Assigned",
                "assigned_assets": ["Rescue Team 05"],
                "description": "Stranded interstate train passengers without drinking water supply.",
            },
            {
                "id": "QX-1090",
                "type": "Trapped",
                "priority": "Critical",
                "location": "Zone C / Fishermans Wharf Marina",
                "position": {"x": 27, "y": 28},
                "people": 5,
                "medical_required": True,
                "status": "New",
                "assigned_assets": [],
                "description": "Vessel dragged into seawall; crew signaling distress flares.",
            },
            {
                "id": "QX-1094",
                "type": "Medical emergency",
                "priority": "High",
                "location": "Zone A / Hillside Community Center",
                "position": {"x": 16, "y": 38},
                "people": 7,
                "medical_required": True,
                "status": "In Progress",
                "assigned_assets": ["Ambulance 01"],
                "description": "Elderly evacuees suffering from severe dehydration and shock.",
            },
            {
                "id": "QX-1098",
                "type": "Flood",
                "priority": "Critical",
                "location": "Zone F / West Embankment Causeway",
                "position": {"x": 22, "y": 62},
                "people": 11,
                "medical_required": False,
                "status": "Assigned",
                "assigned_assets": ["Rescue Team 14", "Drone 05"],
                "description": "Levee erosion threatening adjacent 40-home suburban cluster.",
            },
            {
                "id": "QX-1102",
                "type": "Missing person",
                "priority": "High",
                "location": "Zone E / South Arterial Overpass",
                "position": {"x": 45, "y": 78},
                "people": 4,
                "medical_required": False,
                "status": "New",
                "assigned_assets": [],
                "description": "Two vehicles submerged under overpass; occupants unaccounted for.",
            },
            {
                "id": "QX-1106",
                "type": "Chemical hazard",
                "priority": "Critical",
                "location": "Zone D / Solar Grid Transformer Yard",
                "position": {"x": 72, "y": 40},
                "people": 2,
                "medical_required": True,
                "status": "Assigned",
                "assigned_assets": ["Rescue Team 02"],
                "description": "Dielectric fluid spill interacting with storm runoff.",
            },
            {
                "id": "QX-1110",
                "type": "Trapped",
                "priority": "High",
                "location": "Zone I / Downtown Metro Underground",
                "position": {"x": 52, "y": 38},
                "people": 22,
                "medical_required": False,
                "status": "In Progress",
                "assigned_assets": ["Rescue Team 18", "Drone 08"],
                "description": "Subway station entrance flooded; 22 riders trapped in mezzanine concourse.",
            },
            {
                "id": "QX-1114",
                "type": "Food / water",
                "priority": "Medium",
                "location": "Zone J / South Valley Community Sports Field",
                "position": {"x": 76, "y": 68},
                "people": 35,
                "medical_required": False,
                "status": "New",
                "assigned_assets": [],
                "description": "Neighborhood congregation point urgently requesting infant formula and meals.",
            },
            {
                "id": "QX-1118",
                "type": "Medical emergency",
                "priority": "Critical",
                "location": "Zone H / Medical Research Wing 3",
                "position": {"x": 38, "y": 82},
                "people": 6,
                "medical_required": True,
                "status": "Assigned",
                "assigned_assets": ["Ambulance 06", "Rescue Team 06"],
                "description": "Lab technicians exposed to fumes after emergency generator backfire.",
            },
            {
                "id": "QX-1122",
                "type": "Structural damage",
                "priority": "Medium",
                "location": "Zone G / Container Terminal Crane 4",
                "position": {"x": 88, "y": 32},
                "people": 1,
                "medical_required": False,
                "status": "New",
                "assigned_assets": [],
                "description": "Gantry crane listing 15 degrees towards primary access highway.",
            },
            {
                "id": "QX-1126",
                "type": "Trapped",
                "priority": "High",
                "location": "Zone A / North Boulevard Bridge Pedestrian Span",
                "position": {"x": 19, "y": 26},
                "people": 5,
                "medical_required": False,
                "status": "Assigned",
                "assigned_assets": ["Rescue Team 01"],
                "description": "Cyclists and pedestrians cut off on elevated bridge ramp.",
            },
            {
                "id": "QX-1130",
                "type": "Flood",
                "priority": "Critical",
                "location": "Zone B / City Hall Annex Basements",
                "position": {"x": 46, "y": 42},
                "people": 7,
                "medical_required": True,
                "status": "Assigned",
                "assigned_assets": ["Rescue Team 10", "Drone 02"],
                "description": "Civil defense staff trapped in underground dispatch communications hub.",
            },
            {
                "id": "QX-1134",
                "type": "Food / water",
                "priority": "Low",
                "location": "Zone E / West Expressway Culvert",
                "position": {"x": 39, "y": 68},
                "people": 14,
                "medical_required": False,
                "status": "New",
                "assigned_assets": [],
                "description": "Local community volunteer brigade requests clean drinking water.",
            },
            {
                "id": "QX-1138",
                "type": "Missing person",
                "priority": "Medium",
                "location": "Zone C / Northshore Marina Boardwalk",
                "position": {"x": 35, "y": 18},
                "people": 2,
                "medical_required": False,
                "status": "In Progress",
                "assigned_assets": ["Drone 07"],
                "description": "Search in progress along boardwalk perimeter for missing kayakers.",
            },
        ],
        "drones": [
            {
                "id": f"DRONE-{index + 1:02d}",
                "status": "Charging" if index == 1 else "Idle" if index == 6 else "Active",
                "battery": [92, 43, 74, 67, 88, 53, 100, 61][index],
                "position": {
                    "x": [22, 35, 30, 48, 57, 63, 76, 42][index],
                    "y": [26, 28, 38, 31, 43, 58, 28, 70][index],
                },
                "altitude": [150, 0, 120, 135, 145, 118, 0, 126][index],
                "mission": [
                    "Mapping Zone A & C",
                    "Charging Base North",
                    "Search Riverside Towers",
                    "Damage scan Zone D",
                    "Survivor detection Zone B",
                    "Supply overwatch Zone F",
                    "Standby East Hub",
                    "Route survey Canal Bridge",
                ][index],
                "signal": [98, 100, 96, 91, 87, 94, 100, 89][index],
                "search_radius": [420, 0, 510, 390, 470, 440, 0, 410][index],
                "people_detected": [3, 0, 8, 1, 6, 2, 0, 4][index],
            }
            for index in range(8)
        ],
        "rescue_teams": [
            {
                "id": f"TEAM-{index + 1:02d}",
                "type": [
                    "Medical",
                    "Fire & Rescue",
                    "Search & Rescue",
                    "Engineering",
                    "Road Clearance",
                ][index % 5],
                "location": [
                    "North Hub",
                    "Riverside Station",
                    "Market Square Post",
                    "Canal Bridge Base",
                    "Central Shelter",
                    "East Port Base",
                    "South Suburb Command",
                ][index % 7],
                "position": {
                    "x": 16 + (index * 13) % 68,
                    "y": 16 + (index * 19) % 64,
                },
                "availability": "Assigned" if index < 17 else "Available",
                "capacity": 4 + index % 5,
                "mission": f"Incident QX-{1047 + (index * 4)}"
                if index < 17
                else "Awaiting tasking",
                "eta": 5 + (index * 3) % 20,
            }
            for index in range(21)
        ],
        "roads": roads(),
        "shelters": shelters(),
        "hospitals": hospitals(),
        "resources": resources(),
        "missions": [
            {
                "id": "M-01",
                "asset_id": "DRONE-03",
                "target": "Zone C flood scan",
                "status": "Active",
                "eta": 6,
            },
            {
                "id": "M-02",
                "asset_id": "TEAM-12",
                "target": "Riverside extraction",
                "status": "Active",
                "eta": 11,
            },
            {
                "id": "M-03",
                "asset_id": "AMB-07",
                "target": "Hospital North transfer",
                "status": "Queued",
                "eta": 14,
            },
            {
                "id": "M-04",
                "asset_id": "DRONE-01",
                "target": "Northern Heights perimeter",
                "status": "Active",
                "eta": 8,
            },
            {
                "id": "M-05",
                "asset_id": "TEAM-16",
                "target": "Pinecrest Care extraction",
                "status": "En Route",
                "eta": 15,
            },
        ],
        "disclaimer": "Educational simulation only. Not real emergency data.",
    }


def create_simulation(payload: SimulationCreateRequest) -> dict:
    density = {"Low": 0.72, "Medium": 1.0, "High": 1.34}[payload.population_density]
    affected = round(payload.severity * 4.65 * density)
    return {
        **demo_state(),
        "disaster": {
            "type": payload.disaster_type,
            "severity": payload.severity,
            "population_density": payload.population_density,
            "road_blockage": payload.road_blockage,
            "affected_population": affected,
            "active_incidents": max(4, round(payload.severity / 4.2)),
            "blocked_roads": max(1, round(payload.road_blockage / 3.8)),
            "status": "Running",
        },
        "scenario_inputs": payload.model_dump(),
    }


def whatif_simulation(payload: SimulationCreateRequest) -> dict:
    """Recalculate scenario without fully regenerating state."""
    density = {"Low": 0.72, "Medium": 1.0, "High": 1.34}[payload.population_density]
    affected = round(payload.severity * 4.65 * density)
    incidents = max(4, round(payload.severity / 4.2))
    blocked = max(1, round(payload.road_blockage / 3.8))
    return {
        "disaster_type": payload.disaster_type,
        "severity": payload.severity,
        "affected_population": affected,
        "active_incidents": incidents,
        "blocked_roads": blocked,
        "updated_actions": [
            f"{max(1, round(payload.severity / 28))} drones reassigned",
            f"{max(1, round(payload.road_blockage / 12))} ambulances rerouted",
            f"{max(1, round(payload.severity / 42))} rescue teams deployed",
            f"{round(affected * 0.38)} people redirected to safer shelters",
            "Water and medicine allocations increased"
            if payload.severity > 70
            else "Fuel and food distribution rebalanced",
        ],
        "disclaimer": "Simulated what-if recalculation.",
    }


def shelters() -> list[dict]:
    return [
        {
            "id": "S-01",
            "name": "Central High School Gym",
            "position": {"x": 47, "y": 19},
            "capacity": 550,
            "occupied": 345,
            "distance_km": 3.2,
            "risk_level": "Low",
            "medical_support": True,
            "accessibility": "Open",
        },
        {
            "id": "S-02",
            "name": "North Multi-Sport Arena",
            "position": {"x": 21, "y": 11},
            "capacity": 750,
            "occupied": 610,
            "distance_km": 5.8,
            "risk_level": "Low",
            "medical_support": True,
            "accessibility": "Open",
        },
        {
            "id": "S-03",
            "name": "Railway Heritage Hall",
            "position": {"x": 69, "y": 19},
            "capacity": 420,
            "occupied": 290,
            "distance_km": 4.0,
            "risk_level": "Medium",
            "medical_support": False,
            "accessibility": "Limited",
        },
        {
            "id": "S-04",
            "name": "South Valley College",
            "position": {"x": 79, "y": 81},
            "capacity": 650,
            "occupied": 310,
            "distance_km": 8.1,
            "risk_level": "Low",
            "medical_support": True,
            "accessibility": "Open",
        },
        {
            "id": "S-05",
            "name": "Civic Exhibition Center",
            "position": {"x": 37, "y": 79},
            "capacity": 380,
            "occupied": 320,
            "distance_km": 6.7,
            "risk_level": "High",
            "medical_support": False,
            "accessibility": "Limited",
        },
        {
            "id": "S-06",
            "name": "East Sports Complex",
            "position": {"x": 88, "y": 43},
            "capacity": 240,
            "occupied": 195,
            "distance_km": 7.4,
            "risk_level": "Medium",
            "medical_support": False,
            "accessibility": "Open",
        },
        {
            "id": "S-07",
            "name": "West Harbor Community Hub",
            "position": {"x": 14, "y": 46},
            "capacity": 320,
            "occupied": 215,
            "distance_km": 4.8,
            "risk_level": "Low",
            "medical_support": True,
            "accessibility": "Open",
        },
        {
            "id": "S-08",
            "name": "University Field House",
            "position": {"x": 32, "y": 66},
            "capacity": 480,
            "occupied": 290,
            "distance_km": 5.3,
            "risk_level": "Low",
            "medical_support": True,
            "accessibility": "Open",
        },
        {
            "id": "S-09",
            "name": "Northgate Community Church",
            "position": {"x": 18, "y": 32},
            "capacity": 260,
            "occupied": 180,
            "distance_km": 3.9,
            "risk_level": "Low",
            "medical_support": False,
            "accessibility": "Open",
        },
        {
            "id": "S-10",
            "name": "Metro Stadium Pavilion",
            "position": {"x": 56, "y": 34},
            "capacity": 800,
            "occupied": 540,
            "distance_km": 2.7,
            "risk_level": "Low",
            "medical_support": True,
            "accessibility": "Open",
        },
        {
            "id": "S-11",
            "name": "Valley Baptist Shelter",
            "position": {"x": 74, "y": 58},
            "capacity": 310,
            "occupied": 240,
            "distance_km": 6.2,
            "risk_level": "Medium",
            "medical_support": False,
            "accessibility": "Open",
        },
        {
            "id": "S-12",
            "name": "Hillcrest Academy Hall",
            "position": {"x": 29, "y": 86},
            "capacity": 390,
            "occupied": 220,
            "distance_km": 7.8,
            "risk_level": "Low",
            "medical_support": True,
            "accessibility": "Open",
        },
        {
            "id": "S-13",
            "name": "Riverside Youth Center",
            "position": {"x": 42, "y": 30},
            "capacity": 290,
            "occupied": 260,
            "distance_km": 2.1,
            "risk_level": "High",
            "medical_support": False,
            "accessibility": "Limited",
        },
        {
            "id": "S-14",
            "name": "Eastside YMCA Facility",
            "position": {"x": 84, "y": 62},
            "capacity": 350,
            "occupied": 210,
            "distance_km": 7.9,
            "risk_level": "Low",
            "medical_support": True,
            "accessibility": "Open",
        },
    ]


def hospitals() -> list[dict]:
    return [
        {
            "id": "H-01",
            "name": "Hospital North Medical Center",
            "position": {"x": 18, "y": 22},
            "capacity": 280,
            "icu_capacity": 45,
            "emergency_beds": 34,
            "doctors_available": 19,
            "ambulances_available": 4,
            "current_patients": 218,
        },
        {
            "id": "H-02",
            "name": "Central Trauma & Surgical Center",
            "position": {"x": 53, "y": 26},
            "capacity": 360,
            "icu_capacity": 62,
            "emergency_beds": 48,
            "doctors_available": 28,
            "ambulances_available": 6,
            "current_patients": 265,
        },
        {
            "id": "H-03",
            "name": "South Field Emergency Hospital",
            "position": {"x": 74, "y": 71},
            "capacity": 190,
            "icu_capacity": 26,
            "emergency_beds": 38,
            "doctors_available": 15,
            "ambulances_available": 3,
            "current_patients": 89,
        },
        {
            "id": "H-04",
            "name": "Westside General Memorial",
            "position": {"x": 15, "y": 62},
            "capacity": 240,
            "icu_capacity": 38,
            "emergency_beds": 30,
            "doctors_available": 16,
            "ambulances_available": 4,
            "current_patients": 178,
        },
        {
            "id": "H-05",
            "name": "Harbor Emergency Clinic & Triage",
            "position": {"x": 84, "y": 22},
            "capacity": 160,
            "icu_capacity": 20,
            "emergency_beds": 24,
            "doctors_available": 11,
            "ambulances_available": 2,
            "current_patients": 112,
        },
        {
            "id": "H-06",
            "name": "University Children's Hospital",
            "position": {"x": 36, "y": 72},
            "capacity": 220,
            "icu_capacity": 36,
            "emergency_beds": 28,
            "doctors_available": 22,
            "ambulances_available": 3,
            "current_patients": 145,
        },
        {
            "id": "H-07",
            "name": "St. Jude Community Health Wing",
            "position": {"x": 62, "y": 54},
            "capacity": 180,
            "icu_capacity": 24,
            "emergency_beds": 22,
            "doctors_available": 13,
            "ambulances_available": 3,
            "current_patients": 124,
        },
        {
            "id": "H-08",
            "name": "Highland Regional Trauma Post",
            "position": {"x": 42, "y": 88},
            "capacity": 150,
            "icu_capacity": 18,
            "emergency_beds": 20,
            "doctors_available": 10,
            "ambulances_available": 2,
            "current_patients": 68,
        },
    ]


def roads() -> list[dict]:
    return [
        {
            "id": "RD-01",
            "from_position": {"x": 12, "y": 28},
            "to_position": {"x": 88, "y": 28},
            "distance_km": 9.1,
            "travel_time_min": 16,
            "congestion": 48,
            "blockage": 0,
            "risk": 22,
        },
        {
            "id": "RD-02",
            "from_position": {"x": 18, "y": 52},
            "to_position": {"x": 82, "y": 52},
            "distance_km": 7.7,
            "travel_time_min": 21,
            "congestion": 72,
            "blockage": 44,
            "risk": 58,
        },
        {
            "id": "RD-03",
            "from_position": {"x": 26, "y": 82},
            "to_position": {"x": 78, "y": 14},
            "distance_km": 12.4,
            "travel_time_min": 32,
            "congestion": 69,
            "blockage": 76,
            "risk": 74,
        },
        {
            "id": "RD-04",
            "from_position": {"x": 38, "y": 16},
            "to_position": {"x": 38, "y": 88},
            "distance_km": 8.2,
            "travel_time_min": 18,
            "congestion": 53,
            "blockage": 12,
            "risk": 31,
        },
        {
            "id": "RD-05",
            "from_position": {"x": 63, "y": 12},
            "to_position": {"x": 63, "y": 86},
            "distance_km": 8.7,
            "travel_time_min": 22,
            "congestion": 64,
            "blockage": 30,
            "risk": 46,
        },
        {
            "id": "RD-06",
            "from_position": {"x": 10, "y": 73},
            "to_position": {"x": 91, "y": 39},
            "distance_km": 10.8,
            "travel_time_min": 27,
            "congestion": 59,
            "blockage": 67,
            "risk": 61,
        },
        {
            "id": "RD-07",
            "from_position": {"x": 18, "y": 22},
            "to_position": {"x": 47, "y": 19},
            "distance_km": 4.2,
            "travel_time_min": 9,
            "congestion": 35,
            "blockage": 0,
            "risk": 18,
        },
        {
            "id": "RD-08",
            "from_position": {"x": 47, "y": 19},
            "to_position": {"x": 53, "y": 26},
            "distance_km": 3.1,
            "travel_time_min": 7,
            "congestion": 42,
            "blockage": 15,
            "risk": 25,
        },
        {
            "id": "RD-09",
            "from_position": {"x": 53, "y": 26},
            "to_position": {"x": 84, "y": 22},
            "distance_km": 5.6,
            "travel_time_min": 12,
            "congestion": 55,
            "blockage": 20,
            "risk": 38,
        },
        {
            "id": "RD-10",
            "from_position": {"x": 15, "y": 62},
            "to_position": {"x": 36, "y": 72},
            "distance_km": 4.8,
            "travel_time_min": 14,
            "congestion": 60,
            "blockage": 35,
            "risk": 42,
        },
        {
            "id": "RD-11",
            "from_position": {"x": 36, "y": 72},
            "to_position": {"x": 62, "y": 54},
            "distance_km": 6.2,
            "travel_time_min": 16,
            "congestion": 51,
            "blockage": 18,
            "risk": 29,
        },
        {
            "id": "RD-12",
            "from_position": {"x": 62, "y": 54},
            "to_position": {"x": 74, "y": 71},
            "distance_km": 4.4,
            "travel_time_min": 11,
            "congestion": 45,
            "blockage": 25,
            "risk": 36,
        },
        {
            "id": "RD-13",
            "from_position": {"x": 21, "y": 11},
            "to_position": {"x": 18, "y": 22},
            "distance_km": 2.8,
            "travel_time_min": 6,
            "congestion": 28,
            "blockage": 0,
            "risk": 14,
        },
        {
            "id": "RD-14",
            "from_position": {"x": 14, "y": 46},
            "to_position": {"x": 15, "y": 62},
            "distance_km": 3.4,
            "travel_time_min": 8,
            "congestion": 39,
            "blockage": 10,
            "risk": 21,
        },
        {
            "id": "RD-15",
            "from_position": {"x": 37, "y": 79},
            "to_position": {"x": 42, "y": 88},
            "distance_km": 2.9,
            "travel_time_min": 8,
            "congestion": 48,
            "blockage": 40,
            "risk": 52,
        },
        {
            "id": "RD-16",
            "from_position": {"x": 69, "y": 19},
            "to_position": {"x": 88, "y": 43},
            "distance_km": 5.2,
            "travel_time_min": 13,
            "congestion": 62,
            "blockage": 22,
            "risk": 35,
        },
        {
            "id": "RD-17",
            "from_position": {"x": 74, "y": 58},
            "to_position": {"x": 79, "y": 81},
            "distance_km": 4.1,
            "travel_time_min": 10,
            "congestion": 38,
            "blockage": 12,
            "risk": 28,
        },
        {
            "id": "RD-18",
            "from_position": {"x": 56, "y": 34},
            "to_position": {"x": 62, "y": 54},
            "distance_km": 3.7,
            "travel_time_min": 9,
            "congestion": 44,
            "blockage": 15,
            "risk": 26,
        },
    ]


def resources() -> list[dict]:
    return [
        {
            "id": "R-WATER",
            "name": "Water",
            "stock_percent": 81,
            "units": 18400,
            "unit_name": "liters",
            "trend": -9,
        },
        {
            "id": "R-FOOD",
            "name": "Food",
            "stock_percent": 67,
            "units": 5200,
            "unit_name": "meals",
            "trend": -6,
        },
        {
            "id": "R-MED",
            "name": "Medicine",
            "stock_percent": 42,
            "units": 920,
            "unit_name": "kits",
            "trend": -11,
        },
        {
            "id": "R-BLANKETS",
            "name": "Blankets",
            "stock_percent": 58,
            "units": 1710,
            "unit_name": "units",
            "trend": -4,
        },
        {
            "id": "R-FUEL",
            "name": "Fuel",
            "stock_percent": 21,
            "units": 3100,
            "unit_name": "liters",
            "trend": -14,
        },
        {
            "id": "R-EQUIP",
            "name": "Rescue Equipment",
            "stock_percent": 73,
            "units": 146,
            "unit_name": "sets",
            "trend": -3,
        },
    ]
