import type { SimulationState } from "@/types/domain";

const now = new Date("2026-09-11T09:00:00+05:30").toISOString();

export const demoSimulation: SimulationState = {
  disaster: {
    type: "Flood",
    severity: 78,
    populationDensity: "High",
    roadBlockage: 54,
    affectedPopulation: 640,
    activeIncidents: 24,
    blockedRoads: 18,
    status: "Running"
  },
  incidents: [
    {
      id: "QX-1047",
      type: "Trapped",
      priority: "Critical",
      location: "Zone C / Riverside Towers Complex",
      position: { x: 31, y: 35 },
      people: 6,
      medicalRequired: true,
      status: "Assigned",
      assignedAssets: ["DRONE-03", "AMB-07", "TEAM-12"],
      createdAt: now,
      description: "People trapped on 3rd floor balconies with rising water levels."
    },
    {
      id: "QX-1051",
      type: "Medical emergency",
      priority: "Critical",
      location: "Zone B / Central Market Square",
      position: { x: 43, y: 51 },
      people: 4,
      medicalRequired: true,
      status: "In Progress",
      assignedAssets: ["AMB-02", "TEAM-04"],
      createdAt: now,
      description: "Severe hypothermia and trauma victims awaiting extraction."
    },
    {
      id: "QX-1055",
      type: "Food / water",
      priority: "High",
      location: "Zone F / Old Bus Depot & Terminal",
      position: { x: 61, y: 44 },
      people: 28,
      medicalRequired: false,
      status: "Assigned",
      assignedAssets: ["TEAM-08", "DRONE-06"],
      createdAt: now,
      description: "Stranded commuters require emergency rations and potable water."
    },
    {
      id: "QX-1059",
      type: "Structural damage",
      priority: "High",
      location: "Zone E / Canal Bridge & Sluice Gate",
      position: { x: 52, y: 65 },
      people: 9,
      medicalRequired: false,
      status: "New",
      assignedAssets: [],
      createdAt: now,
      description: "Bridge support compromised by flood debris; traffic halted."
    },
    {
      id: "QX-1062",
      type: "Trapped",
      priority: "Critical",
      location: "Zone A / Northern Residential Heights",
      position: { x: 22, y: 42 },
      people: 8,
      medicalRequired: true,
      status: "Assigned",
      assignedAssets: ["TEAM-03", "DRONE-01"],
      createdAt: now,
      description: "Multiple families trapped in basement units as flood walls breached."
    },
    {
      id: "QX-1066",
      type: "Missing person",
      priority: "High",
      location: "Zone D / East Industrial Park Bay 4",
      position: { x: 68, y: 32 },
      people: 3,
      medicalRequired: false,
      status: "In Progress",
      assignedAssets: ["DRONE-04", "TEAM-07"],
      createdAt: now,
      description: "Warehouse security personnel unaccounted for following storm surge."
    },
    {
      id: "QX-1070",
      type: "Fire",
      priority: "Medium",
      location: "Zone B / Metro Electrical Substation",
      position: { x: 48, y: 56 },
      people: 0,
      medicalRequired: false,
      status: "Assigned",
      assignedAssets: ["TEAM-09"],
      createdAt: now,
      description: "Transformer explosion following storm floodwater infiltration."
    },
    {
      id: "QX-1074",
      type: "Trapped",
      priority: "Critical",
      location: "Zone G / Coastal Harbor Pier 9 Warehouse",
      position: { x: 82, y: 28 },
      people: 12,
      medicalRequired: true,
      status: "New",
      assignedAssets: [],
      createdAt: now,
      description: "Dock workers cut off on container roof by tidal surge."
    },
    {
      id: "QX-1078",
      type: "Medical emergency",
      priority: "Critical",
      location: "Zone J / Pinecrest Senior Care Pavilion",
      position: { x: 70, y: 72 },
      people: 15,
      medicalRequired: true,
      status: "Assigned",
      assignedAssets: ["AMB-05", "AMB-09", "TEAM-16"],
      createdAt: now,
      description: "Power failure disabled medical respirators; urgent evacuation required."
    },
    {
      id: "QX-1082",
      type: "Structural damage",
      priority: "High",
      location: "Zone H / University Tech Campus Quad",
      position: { x: 34, y: 76 },
      people: 18,
      medicalRequired: false,
      status: "In Progress",
      assignedAssets: ["TEAM-11"],
      createdAt: now,
      description: "Research building roof collapse; students sheltered in laboratory wing."
    },
    {
      id: "QX-1086",
      type: "Food / water",
      priority: "Medium",
      location: "Zone I / Grand Central Railway Concourse",
      position: { x: 58, y: 22 },
      people: 42,
      medicalRequired: false,
      status: "Assigned",
      assignedAssets: ["TEAM-05"],
      createdAt: now,
      description: "Stranded interstate train passengers without drinking water supply."
    },
    {
      id: "QX-1090",
      type: "Trapped",
      priority: "Critical",
      location: "Zone C / Fishermans Wharf Marina",
      position: { x: 27, y: 28 },
      people: 5,
      medicalRequired: true,
      status: "New",
      assignedAssets: [],
      createdAt: now,
      description: "Vessel dragged into seawall; crew signaling distress flares."
    },
    {
      id: "QX-1094",
      type: "Medical emergency",
      priority: "High",
      location: "Zone A / Hillside Community Center",
      position: { x: 16, y: 38 },
      people: 7,
      medicalRequired: true,
      status: "In Progress",
      assignedAssets: ["AMB-01"],
      createdAt: now,
      description: "Elderly evacuees suffering from severe dehydration and shock."
    },
    {
      id: "QX-1098",
      type: "Flood",
      priority: "Critical",
      location: "Zone F / West Embankment Causeway",
      position: { x: 22, y: 62 },
      people: 11,
      medicalRequired: false,
      status: "Assigned",
      assignedAssets: ["TEAM-14", "DRONE-05"],
      createdAt: now,
      description: "Levee erosion threatening adjacent 40-home suburban cluster."
    },
    {
      id: "QX-1102",
      type: "Missing person",
      priority: "High",
      location: "Zone E / South Arterial Overpass",
      position: { x: 45, y: 78 },
      people: 4,
      medicalRequired: false,
      status: "New",
      assignedAssets: [],
      createdAt: now,
      description: "Two vehicles submerged under overpass; occupants unaccounted for."
    },
    {
      id: "QX-1106",
      type: "Chemical hazard",
      priority: "Critical",
      location: "Zone D / Solar Grid Transformer Yard",
      position: { x: 72, y: 40 },
      people: 2,
      medicalRequired: true,
      status: "Assigned",
      assignedAssets: ["TEAM-02"],
      createdAt: now,
      description: "Dielectric fluid spill interacting with storm runoff."
    },
    {
      id: "QX-1110",
      type: "Trapped",
      priority: "High",
      location: "Zone I / Downtown Metro Underground",
      position: { x: 52, y: 38 },
      people: 22,
      medicalRequired: false,
      status: "In Progress",
      assignedAssets: ["TEAM-18", "DRONE-08"],
      createdAt: now,
      description: "Subway station entrance flooded; 22 riders trapped in mezzanine concourse."
    },
    {
      id: "QX-1114",
      type: "Food / water",
      priority: "Medium",
      location: "Zone J / South Valley Community Sports Field",
      position: { x: 76, y: 68 },
      people: 35,
      medicalRequired: false,
      status: "New",
      assignedAssets: [],
      createdAt: now,
      description: "Neighborhood congregation point urgently requesting infant formula and meals."
    },
    {
      id: "QX-1118",
      type: "Medical emergency",
      priority: "Critical",
      location: "Zone H / Medical Research Wing 3",
      position: { x: 38, y: 82 },
      people: 6,
      medicalRequired: true,
      status: "Assigned",
      assignedAssets: ["AMB-06", "TEAM-06"],
      createdAt: now,
      description: "Lab technicians exposed to fumes after emergency generator backfire."
    },
    {
      id: "QX-1122",
      type: "Structural damage",
      priority: "Medium",
      location: "Zone G / Container Terminal Crane 4",
      position: { x: 88, y: 32 },
      people: 1,
      medicalRequired: false,
      status: "New",
      assignedAssets: [],
      createdAt: now,
      description: "Gantry crane listing 15 degrees towards primary access highway."
    },
    {
      id: "QX-1126",
      type: "Trapped",
      priority: "High",
      location: "Zone A / North Boulevard Bridge Pedestrian Span",
      position: { x: 19, y: 26 },
      people: 5,
      medicalRequired: false,
      status: "Assigned",
      assignedAssets: ["TEAM-01"],
      createdAt: now,
      description: "Cyclists and pedestrians cut off on elevated bridge ramp."
    },
    {
      id: "QX-1130",
      type: "Flood",
      priority: "Critical",
      location: "Zone B / City Hall Annex Basements",
      position: { x: 46, y: 42 },
      people: 7,
      medicalRequired: true,
      status: "Assigned",
      assignedAssets: ["TEAM-10", "DRONE-02"],
      createdAt: now,
      description: "Civil defense staff trapped in underground dispatch communications hub."
    },
    {
      id: "QX-1134",
      type: "Food / water",
      priority: "Low",
      location: "Zone E / West Expressway Culvert",
      position: { x: 39, y: 68 },
      people: 14,
      medicalRequired: false,
      status: "New",
      assignedAssets: [],
      createdAt: now,
      description: "Local community volunteer brigade requests clean drinking water."
    },
    {
      id: "QX-1138",
      type: "Missing person",
      priority: "Medium",
      location: "Zone C / Northshore Marina Boardwalk",
      position: { x: 35, y: 18 },
      people: 2,
      medicalRequired: false,
      status: "In Progress",
      assignedAssets: ["DRONE-07"],
      createdAt: now,
      description: "Search in progress along boardwalk perimeter for missing kayakers."
    }
  ],
  peopleGroups: [
    { id: "PG-A", zone: "Zone A", count: 96, risk: "High", medicalNeed: false, position: { x: 20, y: 36 } },
    { id: "PG-B", zone: "Zone B", count: 148, risk: "Critical", medicalNeed: true, position: { x: 44, y: 47 } },
    { id: "PG-C", zone: "Zone C", count: 112, risk: "Critical", medicalNeed: true, position: { x: 30, y: 32 } },
    { id: "PG-D", zone: "Zone D", count: 74, risk: "Medium", medicalNeed: false, position: { x: 68, y: 36 } },
    { id: "PG-E", zone: "Zone E", count: 62, risk: "High", medicalNeed: false, position: { x: 48, y: 68 } },
    { id: "PG-F", zone: "Zone F", count: 58, risk: "High", medicalNeed: false, position: { x: 58, y: 46 } },
    { id: "PG-G", zone: "Zone G", count: 44, risk: "Critical", medicalNeed: true, position: { x: 82, y: 30 } },
    { id: "PG-H", zone: "Zone H", count: 52, risk: "Medium", medicalNeed: false, position: { x: 35, y: 78 } },
    { id: "PG-I", zone: "Zone I", count: 66, risk: "High", medicalNeed: true, position: { x: 55, y: 24 } },
    { id: "PG-J", zone: "Zone J", count: 48, risk: "Critical", medicalNeed: true, position: { x: 74, y: 72 } }
  ],
  drones: Array.from({ length: 8 }, (_, index) => ({
    id: `DRONE-${String(index + 1).padStart(2, "0")}`,
    status: index === 1 ? "Charging" : index === 6 ? "Idle" : "Active",
    battery: [92, 43, 74, 67, 88, 53, 100, 61][index],
    position: [
      { x: 22, y: 26 },
      { x: 35, y: 28 },
      { x: 30, y: 38 },
      { x: 48, y: 31 },
      { x: 57, y: 43 },
      { x: 63, y: 58 },
      { x: 76, y: 28 },
      { x: 42, y: 70 }
    ][index],
    altitude: [150, 0, 120, 135, 145, 118, 0, 126][index],
    mission: [
      "Mapping Zone A & C",
      "Charging Base North",
      "Search Riverside Towers",
      "Damage scan Zone D",
      "Survivor detection Zone B",
      "Supply overwatch Zone F",
      "Standby East Hub",
      "Route survey Canal Bridge"
    ][index],
    signal: [98, 100, 96, 91, 87, 94, 100, 89][index],
    searchRadius: [420, 0, 510, 390, 470, 440, 0, 410][index],
    peopleDetected: [3, 0, 8, 1, 6, 2, 0, 4][index]
  })),
  rescueTeams: Array.from({ length: 21 }, (_, index) => {
    const types = ["Medical", "Fire & Rescue", "Search & Rescue", "Engineering", "Road Clearance"] as const;
    const baseLocations = [
      "North Hub",
      "Riverside Station",
      "Market Square Post",
      "Canal Bridge Base",
      "Central Shelter",
      "East Port Base",
      "South Suburb Command"
    ];
    return {
      id: `TEAM-${String(index + 1).padStart(2, "0")}`,
      type: types[index % types.length],
      location: baseLocations[index % baseLocations.length],
      position: { x: 16 + ((index * 13) % 68), y: 16 + ((index * 19) % 64) },
      availability: index % 4 === 0 ? "Available" : index % 4 === 1 ? "Assigned" : index % 4 === 2 ? "En Route" : "Operating",
      capacity: 4 + (index % 5),
      mission: index % 4 === 0 ? "Awaiting tasking" : `Incident QX-${1047 + (index * 4)}`,
      eta: 4 + ((index * 3) % 22)
    };
  }),
  ambulances: Array.from({ length: 12 }, (_, index) => ({
    id: `AMB-${String(index + 1).padStart(2, "0")}`,
    status: index % 3 === 0 ? "Available" : index % 3 === 1 ? "En Route" : "Assigned",
    position: { x: 14 + ((index * 14) % 72), y: 18 + ((index * 11) % 66) },
    patients: index % 3,
    eta: 5 + ((index * 4) % 18)
  })),
  hospitals: [
    {
      id: "H-01",
      name: "Hospital North Medical Center",
      position: { x: 18, y: 22 },
      capacity: 280,
      icuCapacity: 45,
      emergencyBeds: 34,
      doctorsAvailable: 19,
      ambulancesAvailable: 4,
      currentPatients: 218
    },
    {
      id: "H-02",
      name: "Central Trauma & Surgical Center",
      position: { x: 53, y: 26 },
      capacity: 360,
      icuCapacity: 62,
      emergencyBeds: 48,
      doctorsAvailable: 28,
      ambulancesAvailable: 6,
      currentPatients: 265
    },
    {
      id: "H-03",
      name: "South Field Emergency Hospital",
      position: { x: 74, y: 71 },
      capacity: 190,
      icuCapacity: 26,
      emergencyBeds: 38,
      doctorsAvailable: 15,
      ambulancesAvailable: 3,
      currentPatients: 89
    },
    {
      id: "H-04",
      name: "Westside General Memorial",
      position: { x: 15, y: 62 },
      capacity: 240,
      icuCapacity: 38,
      emergencyBeds: 30,
      doctorsAvailable: 16,
      ambulancesAvailable: 4,
      currentPatients: 178
    },
    {
      id: "H-05",
      name: "Harbor Emergency Clinic & Triage",
      position: { x: 84, y: 22 },
      capacity: 160,
      icuCapacity: 20,
      emergencyBeds: 24,
      doctorsAvailable: 11,
      ambulancesAvailable: 2,
      currentPatients: 112
    },
    {
      id: "H-06",
      name: "University Children's Hospital",
      position: { x: 36, y: 72 },
      capacity: 220,
      icuCapacity: 36,
      emergencyBeds: 28,
      doctorsAvailable: 22,
      ambulancesAvailable: 3,
      currentPatients: 145
    },
    {
      id: "H-07",
      name: "St. Jude Community Health Wing",
      position: { x: 62, y: 54 },
      capacity: 180,
      icuCapacity: 24,
      emergencyBeds: 22,
      doctorsAvailable: 13,
      ambulancesAvailable: 3,
      currentPatients: 124
    },
    {
      id: "H-08",
      name: "Highland Regional Trauma Post",
      position: { x: 42, y: 88 },
      capacity: 150,
      icuCapacity: 18,
      emergencyBeds: 20,
      doctorsAvailable: 10,
      ambulancesAvailable: 2,
      currentPatients: 68
    }
  ],
  shelters: [
    {
      id: "S-01",
      name: "Central High School Gym",
      position: { x: 47, y: 19 },
      capacity: 550,
      occupied: 345,
      distanceKm: 3.2,
      riskLevel: "Low",
      medicalSupport: true,
      accessibility: "Open"
    },
    {
      id: "S-02",
      name: "North Multi-Sport Arena",
      position: { x: 21, y: 11 },
      capacity: 750,
      occupied: 610,
      distanceKm: 5.8,
      riskLevel: "Low",
      medicalSupport: true,
      accessibility: "Open"
    },
    {
      id: "S-03",
      name: "Railway Heritage Hall",
      position: { x: 69, y: 19 },
      capacity: 420,
      occupied: 290,
      distanceKm: 4.0,
      riskLevel: "Medium",
      medicalSupport: false,
      accessibility: "Limited"
    },
    {
      id: "S-04",
      name: "South Valley College",
      position: { x: 79, y: 81 },
      capacity: 650,
      occupied: 310,
      distanceKm: 8.1,
      riskLevel: "Low",
      medicalSupport: true,
      accessibility: "Open"
    },
    {
      id: "S-05",
      name: "Civic Exhibition Center",
      position: { x: 37, y: 79 },
      capacity: 380,
      occupied: 320,
      distanceKm: 6.7,
      riskLevel: "High",
      medicalSupport: false,
      accessibility: "Limited"
    },
    {
      id: "S-06",
      name: "East Sports Complex",
      position: { x: 88, y: 43 },
      capacity: 240,
      occupied: 195,
      distanceKm: 7.4,
      riskLevel: "Medium",
      medicalSupport: false,
      accessibility: "Open"
    },
    {
      id: "S-07",
      name: "West Harbor Community Hub",
      position: { x: 14, y: 46 },
      capacity: 320,
      occupied: 215,
      distanceKm: 4.8,
      riskLevel: "Low",
      medicalSupport: true,
      accessibility: "Open"
    },
    {
      id: "S-08",
      name: "University Field House",
      position: { x: 32, y: 66 },
      capacity: 480,
      occupied: 290,
      distanceKm: 5.3,
      riskLevel: "Low",
      medicalSupport: true,
      accessibility: "Open"
    },
    {
      id: "S-09",
      name: "Northgate Community Church",
      position: { x: 18, y: 32 },
      capacity: 260,
      occupied: 180,
      distanceKm: 3.9,
      riskLevel: "Low",
      medicalSupport: false,
      accessibility: "Open"
    },
    {
      id: "S-10",
      name: "Metro Stadium Pavilion",
      position: { x: 56, y: 34 },
      capacity: 800,
      occupied: 540,
      distanceKm: 2.7,
      riskLevel: "Low",
      medicalSupport: true,
      accessibility: "Open"
    },
    {
      id: "S-11",
      name: "Valley Baptist Shelter",
      position: { x: 74, y: 58 },
      capacity: 310,
      occupied: 240,
      distanceKm: 6.2,
      riskLevel: "Medium",
      medicalSupport: false,
      accessibility: "Open"
    },
    {
      id: "S-12",
      name: "Hillcrest Academy Hall",
      position: { x: 29, y: 86 },
      capacity: 390,
      occupied: 220,
      distanceKm: 7.8,
      riskLevel: "Low",
      medicalSupport: true,
      accessibility: "Open"
    },
    {
      id: "S-13",
      name: "Riverside Youth Center",
      position: { x: 42, y: 30 },
      capacity: 290,
      occupied: 260,
      distanceKm: 2.1,
      riskLevel: "High",
      medicalSupport: false,
      accessibility: "Limited"
    },
    {
      id: "S-14",
      name: "Eastside YMCA Facility",
      position: { x: 84, y: 62 },
      capacity: 350,
      occupied: 210,
      distanceKm: 7.9,
      riskLevel: "Low",
      medicalSupport: true,
      accessibility: "Open"
    }
  ],
  resources: [
    { id: "R-WATER", name: "Water", stockPercent: 81, units: 18400, unitName: "liters", trend: -9 },
    { id: "R-FOOD", name: "Food", stockPercent: 67, units: 5200, unitName: "meals", trend: -6 },
    { id: "R-MED", name: "Medicine", stockPercent: 42, units: 920, unitName: "kits", trend: -11 },
    { id: "R-BLANKETS", name: "Blankets", stockPercent: 58, units: 1710, unitName: "units", trend: -4 },
    { id: "R-FUEL", name: "Fuel", stockPercent: 21, units: 3100, unitName: "liters", trend: -14 },
    { id: "R-EQUIP", name: "Rescue Equipment", stockPercent: 73, units: 146, unitName: "sets", trend: -3 }
  ],
  roads: [
    { id: "RD-01", from: { x: 12, y: 28 }, to: { x: 88, y: 28 }, distanceKm: 9.1, travelTimeMin: 16, congestion: 48, blockage: 0, risk: 22 },
    { id: "RD-02", from: { x: 18, y: 52 }, to: { x: 82, y: 52 }, distanceKm: 7.7, travelTimeMin: 21, congestion: 72, blockage: 44, risk: 58 },
    { id: "RD-03", from: { x: 26, y: 82 }, to: { x: 78, y: 14 }, distanceKm: 12.4, travelTimeMin: 32, congestion: 69, blockage: 76, risk: 74 },
    { id: "RD-04", from: { x: 38, y: 16 }, to: { x: 38, y: 88 }, distanceKm: 8.2, travelTimeMin: 18, congestion: 53, blockage: 12, risk: 31 },
    { id: "RD-05", from: { x: 63, y: 12 }, to: { x: 63, y: 86 }, distanceKm: 8.7, travelTimeMin: 22, congestion: 64, blockage: 30, risk: 46 },
    { id: "RD-06", from: { x: 10, y: 73 }, to: { x: 91, y: 39 }, distanceKm: 10.8, travelTimeMin: 27, congestion: 59, blockage: 67, risk: 61 },
    { id: "RD-07", from: { x: 18, y: 22 }, to: { x: 47, y: 19 }, distanceKm: 4.2, travelTimeMin: 9, congestion: 35, blockage: 0, risk: 18 },
    { id: "RD-08", from: { x: 47, y: 19 }, to: { x: 53, y: 26 }, distanceKm: 3.1, travelTimeMin: 7, congestion: 42, blockage: 15, risk: 25 },
    { id: "RD-09", from: { x: 53, y: 26 }, to: { x: 84, y: 22 }, distanceKm: 5.6, travelTimeMin: 12, congestion: 55, blockage: 20, risk: 38 },
    { id: "RD-10", from: { x: 15, y: 62 }, to: { x: 36, y: 72 }, distanceKm: 4.8, travelTimeMin: 14, congestion: 60, blockage: 35, risk: 42 },
    { id: "RD-11", from: { x: 36, y: 72 }, to: { x: 62, y: 54 }, distanceKm: 6.2, travelTimeMin: 16, congestion: 51, blockage: 18, risk: 29 },
    { id: "RD-12", from: { x: 62, y: 54 }, to: { x: 74, y: 71 }, distanceKm: 4.4, travelTimeMin: 11, congestion: 45, blockage: 25, risk: 36 },
    { id: "RD-13", from: { x: 21, y: 11 }, to: { x: 18, y: 22 }, distanceKm: 2.8, travelTimeMin: 6, congestion: 28, blockage: 0, risk: 14 },
    { id: "RD-14", from: { x: 14, y: 46 }, to: { x: 15, y: 62 }, distanceKm: 3.4, travelTimeMin: 8, congestion: 39, blockage: 10, risk: 21 },
    { id: "RD-15", from: { x: 37, y: 79 }, to: { x: 42, y: 88 }, distanceKm: 2.9, travelTimeMin: 8, congestion: 48, blockage: 40, risk: 52 },
    { id: "RD-16", from: { x: 69, y: 19 }, to: { x: 88, y: 43 }, distanceKm: 5.2, travelTimeMin: 13, congestion: 62, blockage: 22, risk: 35 },
    { id: "RD-17", from: { x: 74, y: 58 }, to: { x: 79, y: 81 }, distanceKm: 4.1, travelTimeMin: 10, congestion: 38, blockage: 12, risk: 28 },
    { id: "RD-18", from: { x: 56, y: 34 }, to: { x: 62, y: 54 }, distanceKm: 3.7, travelTimeMin: 9, congestion: 44, blockage: 15, risk: 26 }
  ],
  missions: [
    { id: "M-01", assetId: "DRONE-03", target: "Zone C flood scan", status: "Active", eta: 6 },
    { id: "M-02", assetId: "TEAM-12", target: "Riverside extraction", status: "Active", eta: 11 },
    { id: "M-03", assetId: "AMB-07", target: "Hospital North transfer", status: "Queued", eta: 14 },
    { id: "M-04", assetId: "DRONE-01", target: "Northern Heights perimeter", status: "Active", eta: 8 },
    { id: "M-05", assetId: "TEAM-16", target: "Pinecrest Care extraction", status: "Active", eta: 15 }
  ],
  optimizations: [
    { algorithm: "Classical", objectiveValue: 142.8, executionTimeMs: 830, solutionQuality: 0.91, variables: 12, iterations: 68 },
    {
      algorithm: "QAOA Simulation",
      objectiveValue: 149.2,
      executionTimeMs: 2140,
      solutionQuality: 0.86,
      variables: 12,
      iterations: 40,
      bestBitstring: "101001101010",
      probabilityDistribution: { "101001101010": 0.31, "101001001011": 0.18, "001001101010": 0.14, "101101100010": 0.09 },
      circuitDepth: 34,
      gates: 96
    }
  ],
  updatedActions: [
    "3 drones reassigned to high-risk flood zones",
    "8 ambulances rerouted around blocked arterial corridors",
    "4 road-clearance teams deployed to Canal Bridge and Harbor Road",
    "340 people redirected to Central High School and Multi-Sport Arena",
    "Water and emergency medicine allocation scaled up for Zone B, C, and J"
  ]
};

export const cloneSimulation = (): SimulationState => JSON.parse(JSON.stringify(demoSimulation)) as SimulationState;
